# Generated by Django 5.1.7 on 2025-03-24 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('religion', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('NEVER_MARRIED', 'Never Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('AWAITING_DIVORCE', 'Awaiting Divorce')], max_length=20)),
                ('education', models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('OTHER', 'Other')], max_length=20)),
                ('occupation', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('preferred_age_min', models.IntegerField()),
                ('preferred_age_max', models.IntegerField()),
                ('preferred_height_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_height_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preferred_religion', models.CharField(max_length=100)),
                ('preferred_marital_status', models.CharField(choices=[('NEVER_MARRIED', 'Never Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed'), ('AWAITING_DIVORCE', 'Awaiting Divorce')], max_length=20)),
                ('preferred_education', models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('BACHELORS', "Bachelor's Degree"), ('MASTERS', "Master's Degree"), ('DOCTORATE', 'Doctorate'), ('OTHER', 'Other')], max_length=20)),
                ('preferred_location', models.CharField(max_length=200)),
                ('preferred_income_min', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_income_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
