"""
Django settings for matchmate_backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gri#+ic-w0gry)+_cz#x&xy$uw@gyl8dphyx$-ej98(rsna$(b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'profiles',
    'chat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'matchmate_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'matchmate_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Media files (Uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5176",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Allow all headers and methods during development
CORS_ALLOW_ALL_ORIGINS = True  # Only use this in development!

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    # title of the window
    "site_title": "MatchMate Admin",
    # Title on the login screen
    "site_header": "MatchMate",
    # Title on the brand
    "site_brand": "MatchMate",
    # Welcome text on the login screen
    "welcome_sign": "Welcome to MatchMate Admin",
    # Copyright on the footer
    "copyright": "MatchMate Ltd",
    # The model admin to search from the search bar
    "search_model": "auth.User",
    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "View Site", "url": "http://localhost:5176", "new_window": True},
    ],
    # Whether to display the side menu
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "profiles.Profile": "fas fa-user-circle",
        "profiles.Contact": "fas fa-envelope",
        "chat.Conversation": "fas fa-comments",
        "chat.Message": "fas fa-comment",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-circle",
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    # Change view format
    "changeform_format": "horizontal_tabs",
    # Override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    # Dark mode
    "dark_mode_theme": "darkly",
    # Light mode
    "light_mode_theme": "flatly",
    # Custom CSS for dark mode
    "custom_css_dark": "css/admin-dark.css",
    # Custom CSS for light mode
    "custom_css_light": "css/admin-light.css",
    # Custom CSS for all modes
    "custom_css_all": "css/admin-common.css",
    # Custom JS for all modes
    "custom_js_all": "js/admin-common.js",
    # Custom CSS for the admin interface
    "custom_css_admin": "css/admin.css",
    # Custom JS for the admin interface
    "custom_js_admin": "js/admin.js",
    # Custom CSS for the login page
    "custom_css_login": "css/admin-login.css",
    # Custom JS for the login page
    "custom_js_login": "js/admin-login.js",
    # Custom CSS for the index page
    "custom_css_index": "css/admin-index.css",
    # Custom JS for the index page
    "custom_js_index": "js/admin-index.js",
    # Custom CSS for the change form
    "custom_css_change_form": "css/admin-change-form.css",
    # Custom JS for the change form
    "custom_js_change_form": "js/admin-change-form.js",
    # Custom CSS for the change list
    "custom_css_change_list": "css/admin-change-list.css",
    # Custom JS for the change list
    "custom_js_change_list": "js/admin-change-list.js",
    # Custom colors
    "custom_colors": {
        "primary": "#FF69B4",  # Hot Pink
        "secondary": "#FF1493",  # Deep Pink
        "accent": "#FFB6C1",  # Light Pink
        "success": "#98FB98",  # Pale Green
        "info": "#87CEEB",  # Sky Blue
        "warning": "#FFD700",  # Gold
        "danger": "#FF6B6B",  # Light Red
        "light": "#F8F9FA",
        "dark": "#343A40",
    },
    # Custom fonts
    "custom_fonts": {
        "primary": "Poppins",
        "secondary": "Roboto",
    },
    # Custom styles
    "custom_styles": {
        "navbar": {
            "background": "linear-gradient(135deg, #FF69B4 0%, #FF1493 100%)",
            "color": "#FFFFFF",
        },
        "sidebar": {
            "background": "#343A40",
            "color": "#FFFFFF",
        },
        "content": {
            "background": "#F8F9FA",
            "color": "#343A40",
        },
        "card": {
            "background": "#FFFFFF",
            "border-radius": "10px",
            "box-shadow": "0 2px 4px rgba(0,0,0,0.1)",
        },
        "button": {
            "background": "linear-gradient(135deg, #FF69B4 0%, #FF1493 100%)",
            "color": "#FFFFFF",
            "border-radius": "5px",
            "padding": "8px 16px",
        },
        "input": {
            "border-radius": "5px",
            "border": "1px solid #E9ECEF",
            "padding": "8px 12px",
        },
        "table": {
            "header_background": "#FF69B4",
            "header_color": "#FFFFFF",
            "row_hover_background": "#FFF0F5",
        },
    },
}
